version: "3.5"
services:
  server:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    restart: always
    depends_on:
      - database
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    restart: always
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    restart: always

volumes:
  database-data: